; Script generated by the Inno Setup Script Wizard.
; SEE THE DOCUMENTATION FOR DETAILS ON CREATING INNO SETUP SCRIPT FILES!
; Non-commercial use only

#define MyAppName "Xvoice"
; Keep in step with __version__ in main.py and APP_VERSION in xvoice.spec.
#define MyAppVersion "1.2.0"
#define MyAppPublisher "Shreesha M Rao"
#define MyAppURL "https://xvoicekeyboard.com/"
#define MyAppExeName "xvoice.exe"

[Setup]
; NOTE: The value of AppId uniquely identifies this application. Do not use the same AppId value in installers for other applications.
; (To generate a new GUID, click Tools | Generate GUID inside the IDE.)
AppId={{5D1C7383-6B2A-44E9-B27E-6BD215D4B9E3}
AppName={#MyAppName}
AppVersion={#MyAppVersion}
;AppVerName={#MyAppName} {#MyAppVersion}
AppPublisher={#MyAppPublisher}
AppPublisherURL={#MyAppURL}
AppSupportURL={#MyAppURL}
AppUpdatesURL={#MyAppURL}
DefaultDirName={autopf}\{#MyAppName}
UninstallDisplayIcon={app}\{#MyAppExeName}
; "ArchitecturesAllowed=x64compatible" specifies that Setup cannot run
; on anything but x64 and Windows 11 on Arm.
ArchitecturesAllowed=x64compatible
; "ArchitecturesInstallIn64BitMode=x64compatible" requests that the
; install be done in "64-bit mode" on x64 or Windows 11 on Arm,
; meaning it should use the native 64-bit Program Files directory and
; the 64-bit view of the registry.
ArchitecturesInstallIn64BitMode=x64compatible
DisableProgramGroupPage=yes
; Remove the following line to run in administrative install mode (install for all users).
PrivilegesRequired=lowest
OutputBaseFilename=XVoiceSetup
SolidCompression=yes
WizardStyle=modern dynamic
; Xvoice runs as a tray app with no window, and Windows will not let Setup
; overwrite a running .exe. Without this, Setup left the OLD binary in place and
; every rebuild appeared to change nothing. AppMutex lets Setup see the running
; copy — main.py creates this exact mutex at startup — and close it first.
AppMutex=XvoiceSingleInstanceMutex
CloseApplications=yes
RestartApplications=no

[Languages]
Name: "english"; MessagesFile: "compiler:Default.isl"

[Tasks]
Name: "desktopicon"; Description: "{cm:CreateDesktopIcon}"; GroupDescription: "{cm:AdditionalIcons}"; Flags: unchecked

[InstallDelete]
; Clear the install dir first. A previous one-dir PyInstaller build left a whole
; tree behind, and those stale modules can win over the new single-file exe.
Type: filesandordirs; Name: "{app}\*"

[Files]
; Relative to this .iss file — NEVER hardcode a machine-specific path here.
;
; This line used to read
;   C:\Users\SHREE\OneDrive\Desktop\Projects\Voice-text-keyboard\dist\*
; so the installer packaged whatever exe happened to sit in that one OneDrive
; folder. Building the project anywhere else — a different checkout, a different
; machine, a different user account — changed nothing at all: Setup kept shipping
; the old binary from that fixed path. {#SourcePath} always resolves to the
; directory holding this script, so the installer packages the build you just
; made, wherever you made it.
;
; Named explicitly rather than dist\*, so leftovers from an older one-dir build
; sitting in dist\ are not swept into the installer.
Source: "{#SourcePath}\dist\{#MyAppExeName}"; DestDir: "{app}"; Flags: ignoreversion
; NOTE: Don't use "Flags: ignoreversion" on any shared system files

[Icons]
Name: "{autoprograms}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"
Name: "{autodesktop}\{#MyAppName}"; Filename: "{app}\{#MyAppExeName}"; Tasks: desktopicon

[Run]
Filename: "{app}\{#MyAppExeName}"; Description: "{cm:LaunchProgram,{#StringChange(MyAppName, '&', '&&')}}"; Flags: nowait postinstall skipifsilent

