# -*- mode: python ; coding: utf-8 -*-
# Xvoice PyInstaller spec — produces a single-file executable on
# Windows/Linux and an .app bundle on macOS.

import sys
import os
from PyInstaller.utils.hooks import collect_data_files, collect_submodules, collect_dynamic_libs

block_cipher = None

# Version stamped into Xvoice.app and the DMG name. installer_mac.sh and
# installer_mac_pkg.sh sed this literal back out, so keep the exact
# `APP_VERSION = '...'` form.
#
# MUST match __version__ in main.py and MyAppVersion in installer.iss. The three
# had drifted apart (1.1.0 / 1.2.0 / 1.0), so a log file could not be tied to a
# build and Windows showed the wrong version in Add/Remove Programs.
APP_VERSION = '1.2.0'

# ── Data files & Binaries to bundle ──────────────────────────────────────
datas = []
binaries = []

# PySide6 dynamic DLLs (Qt6Core.dll, Qt6Gui.dll, Qt6Widgets.dll, etc.) & plugins
try:
    binaries += collect_dynamic_libs('PySide6')
    datas += collect_data_files('PySide6')
except Exception:
    pass

if sys.platform == 'win32' and os.path.isfile('ffmpeg.exe'):
    datas.append(('ffmpeg.exe', '.'))

# macOS note — ffmpeg is NOT added here on purpose.
#
# main.py's normalize_audio() looks for a file literally named "ffmpeg.exe"
# beside sys.executable whenever the app is frozen, on every platform.  Inside
# an .app that means Xvoice.app/Contents/MacOS/ffmpeg.exe, but PyInstaller 6
# routes spec-declared binaries to Contents/Frameworks instead.  build_mac.sh
# therefore copies the static mac ffmpeg into Contents/MacOS/ffmpeg.exe as a
# post-build step (the extension is meaningless on macOS; reusing the name
# keeps main.py identical across platforms).  It is optional — without it
# normalize_audio() returns False and the raw recording is transcribed.

# setuptools' vendored jaraco.text ships a data file ("Lorem ipsum.txt")
datas += collect_data_files('setuptools')
try:
    import setuptools as _st
    _jaraco_text = os.path.join(os.path.dirname(_st.__file__), '_vendor', 'jaraco', 'text')
    if os.path.isdir(_jaraco_text):
        for _f in os.listdir(_jaraco_text):
            if _f.endswith('.txt'):
                datas.append((os.path.join(_jaraco_text, _f),
                              os.path.join('setuptools', '_vendor', 'jaraco', 'text')))
except Exception:
    pass

# certifi's CA bundle (cacert.pem)
try:
    import certifi
    datas.append((certifi.where(), 'certifi'))
except Exception:
    pass

pyside_hidden = []
try:
    pyside_hidden = collect_submodules('PySide6')
except Exception:
    pass

# ── macOS: pyobjc bridges ────────────────────────────────────────────────
# pynput's and pystray's Darwin backends reach Quartz / AppKit through the
# pyobjc bridge at runtime, so PyInstaller's static analysis never sees them.
# Without these the frozen .app starts and then silently fails to register the
# F8 hotkey or draw the menu-bar icon.
mac_hidden = []
if sys.platform == 'darwin':
    mac_hidden = [
        'objc',
        'Foundation',
        'AppKit',
        'Quartz',
        'CoreFoundation',
        'ApplicationServices',
        'PyObjCTools',
        'PyObjCTools.AppHelper',
        'pynput.keyboard._darwin',
        'pynput.mouse._darwin',
        'pystray._darwin',
    ]
    for _mod in ('Cocoa', 'Quartz', 'AppKit', 'Foundation'):
        try:
            mac_hidden += collect_submodules(_mod)
        except Exception:
            pass

# ── Icon ─────────────────────────────────────────────────────────────────
# Generated by `python3 mac/make_icns.py` (run automatically by build_mac.sh).
app_icon = None
if sys.platform == 'darwin':
    _icns = os.path.join('mac', 'xvoice.icns')
    if os.path.isfile(_icns):
        app_icon = _icns

a = Analysis(
    ['main.py'],
    pathex=[],
    binaries=binaries,
    datas=datas,
    hiddenimports=[
        'pynput',
        'pynput.keyboard',
        'pynput.keyboard._win32',
        'pynput.keyboard._xorg',
        'pynput.keyboard._darwin',
        'pynput.mouse',
        'pynput.mouse._win32',
        'pynput.mouse._xorg',
        'pynput.mouse._darwin',
        'pystray',
        'pystray._win32',
        'pystray._xorg',
        'pystray._darwin',
        'pyaudio',
        'webrtcvad',
        'PIL',
        'PIL.Image',
        'PIL.ImageDraw',
        'PIL._imaging',
        'PIL._tkinter_finder',
        'requests',
        'json',
        'tempfile',
        'logging',
        'logging.handlers',
        'socket',
        'wave',
        'webbrowser',
        'http.server',
        'pyperclip',
        # ── PySide6 / Qt UI modules ──
        'PySide6',
        'PySide6.QtCore',
        'PySide6.QtGui',
        'PySide6.QtWidgets',
        'shiboken6',
        'writing.engine',
        'writing.overlay',
        'writing.selection',
        'writing.clipboard',
        'writing.backend_client',
        'writing.actions.perform',
        'writing.ui.qt_host',
        'writing.ui.qt_helpers',
        'writing.ui.listening_overlay',
        'writing.ui.action_menu',
        'writing.ui.language_menu',
        'writing.ui.preview_widget',
    ] + pyside_hidden + mac_hidden,
    hookspath=['.'],
    hooksconfig={},
    runtime_hooks=[],
    excludes=[],
    noarchive=False,
)

pyz = PYZ(a.pure, a.zipped_data, cipher=block_cipher)

# ── macOS: produce an .app bundle ───────────────────────────────────────
if sys.platform == 'darwin':
    exe = EXE(
        pyz,
        a.scripts,
        [],
        exclude_binaries=True,
        name='xvoice',
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,
        console=False,
        icon=app_icon,
        target_arch=None,       # native arch; universal2 wheels aren't available
    )
    coll = COLLECT(
        exe,
        a.binaries,
        a.zipfiles,
        a.datas,
        strip=False,
        upx=False,
        name='xvoice',
    )
    app = BUNDLE(
        coll,
        name='Xvoice.app',
        icon=app_icon,
        bundle_identifier='com.xvoicekeyboard.xvoice',
        version=APP_VERSION,
        info_plist={
            'CFBundleName': 'Xvoice',
            'CFBundleDisplayName': 'Xvoice',
            'CFBundleShortVersionString': APP_VERSION,
            'CFBundleVersion': APP_VERSION,
            'CFBundleIdentifier': 'com.xvoicekeyboard.xvoice',
            'CFBundlePackageType': 'APPL',
            'LSUIElement': True,        # menu-bar only, no Dock icon
            'LSMinimumSystemVersion': '11.0',
            'NSHighResolutionCapable': True,
            'NSHumanReadableCopyright':
                'Copyright © Shreesha M Rao. All rights reserved.',
            # ── TCC purpose strings ──
            # macOS kills the app on the spot if it touches one of these
            # subsystems without a matching string in Info.plist.
            'NSMicrophoneUsageDescription':
                'Xvoice needs microphone access to transcribe your speech.',
            'NSAppleEventsUsageDescription':
                'Xvoice uses AppleScript to show notifications and to paste '
                'transcribed text into the app you are using.',
            'NSSystemAdministrationUsageDescription':
                'Xvoice listens for the F8 hotkey system-wide so you can '
                'dictate into any application.',
        },
    )

# ── Windows / Linux: single-file executable ─────────────────────────────
else:
    exe = EXE(
        pyz,
        a.scripts,
        a.binaries,
        a.zipfiles,
        a.datas,
        name='xvoice',
        debug=False,
        bootloader_ignore_signals=False,
        strip=False,
        upx=False,          # no packing — avoids AV false positives
        console=False,      # no terminal window
    )